In [1]:
# Keiana Dunn
# Neural Network - FeedingForward
# Data Analysis 
# 3/1/19
# Objective: Create code takes 5 feature values and computes two targets based 
# on random values for all weights and biases and gives the user the option of choosing 
# either a RELU or a sigmoid function. Computation of the targets is in its own Python 
# function and accept the five features and all weights and biases as input and are output 
# of the targets.



In [2]:
# Import package
import autograd.numpy as np

In [3]:
# You should write your target function in this space
#====================================================

# Define RelU and Sigmoid activation functions

# Rectified Linear Unit (ReLU) used there is a matrix-vector product
def relu(x):
    return np.maximum(x,0)


# Calculate Sigmoid to get output values in a range of 0 to 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
 
#=====================================================

In [4]:
# Network size
N_input = 5
N_hidden1 = 4
N_hidden2 = 3
N_output = 2

np.random.seed(51)

# Weights and Bias Initialization

# Calculate the input to the hidden layer 1 by multiplying neuron weights in hidden layer 1 by neuron weights in input 
weights_in_hidden1 = np.random.rand(N_input,N_hidden1)
# Calculate bias 1 of hidden layer 1
bias1 = np.random.rand(N_hidden1,1)
print('weights_in_hidden1 shape',weights_in_hidden1.shape)
print(weights_in_hidden1)
print("=================================")
print('bias1 shape', bias1.shape)
print(bias1)
print("=================================")

# Calculate the hidden layer 1 to the hidden layer 2 by multiplying neuron weights in hidden layer 2 by neuron weights in hidden layer 1  
weights_in_hidden2 = np.random.rand(N_hidden1,N_hidden2)
print('weights_in_hidden2 shape',weights_in_hidden2.shape)
# Calculate bias 2 of hidden layer 2 
bias2 = np.random.rand(N_hidden2,1)

print(weights_in_hidden2)
print("=================================")
print('bias2 shape', bias2.shape)
print(bias2)
print("=================================")

# Calculate the hidden layer 2 to the output layer by multiplying neuron weights from output by neuron weights in hidden layer 2
weights_in_out = np.random.rand(N_hidden2,N_output)
print('weights_in_out shape',weights_in_out.shape)
# Calculate the bias to output of the network
bias_out = np.random.rand(N_output,1)
print(weights_in_out)
print("===========================")
print('bias_out shape', bias_out.shape)
print(bias_out)


weights_in_hidden1 shape (5, 4)
[[0.67573142 0.04471218 0.34330367 0.64401973]
 [0.284213   0.94933781 0.15767017 0.38797296]
 [0.58999368 0.48779579 0.17434339 0.21818256]
 [0.64674554 0.24983141 0.41024799 0.04772578]
 [0.3235483  0.29220176 0.4454105  0.06027481]]
bias1 shape (4, 1)
[[0.75463839]
 [0.72871083]
 [0.56476094]
 [0.7141214 ]]
weights_in_hidden2 shape (4, 3)
[[0.58235608 0.63913911 0.79519873]
 [0.86949056 0.3499919  0.30789973]
 [0.60372393 0.37214818 0.86377464]
 [0.71159342 0.42302682 0.87715894]]
bias2 shape (3, 1)
[[0.01910321]
 [0.45757318]
 [0.16911379]]
weights_in_out shape (3, 2)
[[0.84287473 0.12445581]
 [0.74292054 0.84760106]
 [0.17438541 0.27141295]]
bias_out shape (2, 1)
[[0.92142313]
 [0.64954718]]


In [5]:
## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
#np.random.shuffle(features_and_targets)

for i in range(22):
    # 22 feature observations 
    features = features_and_targets[i,0:5]
    # 22 target observations
    targets = features_and_targets[i,5:7]
    
# Perform a feedforward through the network using sigmoid activtion function. The weights and biases from 
# input and hidden layers will be put through the activation functions. 
    
    neuron_value_layer2S = sigmoid((np.matmul(features, weights_in_hidden1))+ bias1.T)   
    #print('neuron_value_layer2S shape', neuron_value_layer2.shape)
    print('neuron_value_layer2S')
    print(neuron_value_layer2S)
    print('  ')
  
    neuron_value_layer3S = sigmoid((np.matmul(neuron_value_layer2S, weights_in_hidden2))+ bias2.T)
    print('neuron_value_layer3S')
    print(neuron_value_layer3S)
    print('  ')
    
    neuron_value_layer_outputS = sigmoid((np.matmul(neuron_value_layer3S, weights_in_out))+ bias_out.T)
    print('neuron_value_layer_outputS')
    print(neuron_value_layer_outputS)
    print('  ')
   
    print('  ')  
    print('  ')  
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights
    print('Feature : ',features, ' Target : ', targets)
    
    print(' ')
    print('Observations', i+1,)
  

neuron_value_layer2S
[[0.68018854 0.67452231 0.63755341 0.6713112 ]]
  
neuron_value_layer3S
[[0.86579885 0.83884139 0.88667645]]
  
neuron_value_layer_outputS
[[0.91901206 0.84670124]]
  
  
  
Feature :  [0. 0. 0. 0. 0.]  Target :  [0. 1.]
 
Observations 1
neuron_value_layer2S
[[0.74615068 0.73515032 0.7330537  0.68447111]]
  
neuron_value_layer3S
[[0.88313535 0.85247147 0.90224199]]
  
neuron_value_layer_outputS
[[0.921032   0.84901475]]
  
  
  
Feature :  [0. 0. 0. 0. 1.]  Target :  [0. 1.]
 
Observations 2
neuron_value_layer2S
[[0.84876305 0.78087008 0.80540416 0.69468659]]
  
neuron_value_layer3S
[[0.8977913  0.86610495 0.91602442]]
  
neuron_value_layer_outputS
[[0.92282309 0.85119631]]
  
  
  
Feature :  [0. 0. 0. 1. 1.]  Target :  [0. 1.]
 
Observations 3
neuron_value_layer2S
[[0.91010568 0.85302668 0.83128514 0.73890876]]
  
neuron_value_layer3S
[[0.91039576 0.87650581 0.9256463 ]]
  
neuron_value_layer_outputS
[[0.92423753 0.8528349 ]]
  
  
  
Feature :  [0. 0. 1. 1. 1.] 

Perform a feedforward through the network using sigmoid activtion function

In [6]:
## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
#np.random.shuffle(features_and_targets)

for i in range(22):
    # 22 feature values 
    features = features_and_targets[i,0:5]
    # 22 target values
    targets = features_and_targets[i,5:7]
    #print(features)
    #print(features.shape)
    

# Perform a feedforward through the network using ReLU activtion function. 
# The matrix multiplication will be used for weights and features and biases will be added. 
    
    neuron_value_layer2R = relu((np.matmul(features, weights_in_hidden1))+ bias1.T)   
    #print('neuron_value_layer2R shape', neuron_value_layer2R.shape)
    print('neuron_value_layer2R')
    print(neuron_value_layer2R)
    print('  ')
    
    neuron_value_layer3R = relu((np.matmul(neuron_value_layer2R, weights_in_hidden2))+ bias2.T)
    print('neuron_value_layer3R')
    print(neuron_value_layer3R)
    print('  ')
 
    neuron_value_layer_outputR = relu((np.matmul(neuron_value_layer3R, weights_in_out))+ bias_out.T)
    print('neuron_value_layer_outputR')
    print(neuron_value_layer_outputR)
    print('  ')  
    print('  ')  
    

# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights
    print('Feature : ',features, ' Target : ', targets)
    
    print(' ')
    print('Observations', i+1,)
  
    print(' ')
      
   
    print('  ')  
    

neuron_value_layer2R
[[0.75463839 0.72871083 0.56476094 0.7141214 ]]
  
neuron_value_layer3R
[[1.94130243 1.70720224 2.10779529]]
  
neuron_value_layer_outputR
[[4.19358225 2.9102629 ]]
  
  
Feature :  [0. 0. 0. 0. 0.]  Target :  [0. 1.]
 
Observations 1
 
  
neuron_value_layer2R
[[1.07818669 1.02091259 1.01017144 0.7743962 ]]
  
neuron_value_layer3R
[[2.69558556 2.20751943 2.89265421]]
  
neuron_value_layer_outputR
[[5.33791229 3.64122806]]
  
  
Feature :  [0. 0. 0. 0. 1.]  Target :  [0. 1.]
 
Observations 2
 
  
neuron_value_layer2R
[[1.72493223 1.270744   1.42041943 0.82212198]]
  
neuron_value_layer3R
[[3.57108569 2.8811811  3.88009337]]
  
neuron_value_layer_outputR
[[6.7485213  4.58918925]]
  
  
Feature :  [0. 0. 0. 1. 1.]  Target :  [0. 1.]
 
Observations 3
 
  
neuron_value_layer2R
[[2.31492591 1.75853979 1.59476281 1.04030455]]
  
neuron_value_layer3R
[[4.59931848 3.58617235 4.84142196]]
  
neuron_value_layer_outputR
[[8.30658689 5.57562716]]
  
  
Feature :  [0. 0. 1. 1. 1